server:
  port: 8081
  servlet:
    context-path: /api/v1/admin

spring:
  application:
    name: vima
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vima
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

application:
  security:
    jwt:
      tokenHeader: Authorization
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 300000000000
      refresh-token:
        expiration: 120000